# Generated by Django 4.2.4 on 2023-08-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Назва Аккаунта')),
                ('image', models.ImageField(upload_to='', verbose_name='Зображення')),
                ('full_text', models.TextField(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Добавити пост',
                'verbose_name_plural': 'Добавити пости',
            },
        ),
    ]
